os: linux
dist: focal
language: shell
services:
  - docker
env:
  global:
    - IMAGE_NAME=tronyx/nagios
install:
  - git clone https://github.com/tronyx/Docker-Nagios.git ~/Docker-Nagios
jobs:
  include:
    - stage: Build docker image
      before_script:
        - 'if [[ $TRAVIS_BRANCH == "master" ]]; then docker pull ${IMAGE_NAME} || true; fi'
        - 'if [[ $TRAVIS_BRANCH != "master" ]]; then docker pull ${IMAGE_NAME}:${TRAVIS_BRANCH} || true; fi'
      script:
        - 'if [[ $TRAVIS_BRANCH == "master" ]]; then docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} .; fi'
        - 'if [[ $TRAVIS_BRANCH != "master" ]]; then docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME}:${TRAVIS_BRANCH} .; fi'
    - stage: Test docker image
      script:
        - 'if [[ $TRAVIS_BRANCH == "master" ]]; then docker run -p 8080:80 ${IMAGE_NAME} apache2 -v; fi'
        - 'if [[ $TRAVIS_BRANCH != "master" ]]; then docker run -p 8080:80 ${IMAGE_NAME}:${TRAVIS_BRANCH} apache2 -v; fi'
    - stage: Push docker image
      script:
        - 'if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then echo -n ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin; fi'
        - 'if [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then docker push ${IMAGE_NAME}; fi'
        - 'if [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ ${TRAVIS_BRANCH} != "master" ]]; then docker push ${IMAGE_NAME}:${TRAVIS_BRANCH}; fi'