language: shell
os: linux
dist: bionic
services:
  - docker
install:
  - git clone https://github.com/tronyx/Docker-Nagios.git ~/Docker-Nagios
script:
  # Build image
  - docker build --no-cache=true --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t tronyx/nagios .
  # Test image
  - docker run -p 8080:80 tronyx/nagios apache2 -v
after_success:
  # Push image if not a PR
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" ${DOCKER_REGISTRY}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push tronyx/nagios; fi'