name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Build amd64
        env:
          IMAGE_NAME: tronyx/nagios
        run: |
          docker buildx build --platform linux/amd64 -t ${IMAGE_NAME}:${BRANCH} .

      - name: Build arm64
        env:
          IMAGE_NAME: tronyx/nagios
        run: |
          docker buildx build --platform linux/arm64 -t ${IMAGE_NAME}:${BRANCH} .

      - name: Build armv7
        env:
          IMAGE_NAME: tronyx/nagios
        run: |
          docker buildx build --platform linux/arm/v7 -t ${IMAGE_NAME}:${BRANCH} .

      - name: Build riscv64
        env:
          IMAGE_NAME: tronyx/nagios
        run: |
          docker buildx build --platform linux/riscv64 -t ${IMAGE_NAME}:${BRANCH} .

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifests for DockerHub
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          IMAGE_NAME: tronyx/nagios
        run: |
          SOURCE=${IMAGE_NAME}
          docker manifest create ${IMAGE}:${BRANCH}    --amend ${SOURCE}:linux-amd64 --amend ${SOURCE}:linux-arm64 --amend ${SOURCE}:linux-arm-v7 --amend ${SOURCE}:linux-riscv64 && docker manifest push ${IMAGE}:${BRANCH}
