name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      #- name: Build x86
      #  run: |
      #    docker buildx build --platform linux/386 .

      - name: Build amd64
        run: |
          docker buildx build --platform linux/amd64 .

      - name: Build arm64
        run: |
          docker buildx build --platform linux/arm64 .

      - name: Build armv7
        run: |
          docker buildx build --platform linux/arm/v7 .

      - name: Build riscv64
        run: |
          docker buildx build --platform linux/riscv64 .

